name: Docker PIVPN

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker buildx multiarch
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      - name: docker build docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build . -t $DOCKER_USERNAME/pivpn:latest --platform linux/arm64,linux/amd64 --push

# linux/arm/v5,
# linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8
